version: '2'

services:
  setup:
    networks:
      dockerproxy_default:
    build: .
    logging:
      options:
        max-size: "500k"
    depends_on:
      - mongo-01
      - mongo-02
      - mongo-03
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_S3_BUCKET_NAME=turistforeningen
      - AWS_S3_BUCKET_PATH=/backups/mongo/
    volumes:
      - .:/app
      - ./dump:/dump
      - ./secrets:/secrets
      - ./data:/data

  mongo-01:
    networks:
      dockerproxy_default:
    image: mongo:3
    ports:
      - "27100:27017"
      - "28017"
    expose:
      - "27017"
    logging:
      options:
        max-size: "500k"
    volumes:
      - ./data/db-0:/data/db
    environment:
      - VIRTUAL_HOST=mongo-01.db.dnt.local
      - VIRTUAL_PORT=28017
    command: --noauth --httpinterface --replSet "rs0" --bind_ip 0.0.0.0

  mongo-02:
    networks:
      dockerproxy_default:
    image: mongo:3
    ports:
      - "27200:27017"
      - "28017"
    expose:
      - "27017"
    logging:
      options:
        max-size: "500k"
    volumes:
      - ./data/db-1:/data/db
    environment:
      - VIRTUAL_HOST=mongo-02.db.dnt.local
      - VIRTUAL_PORT=28017
    command: --noauth --httpinterface --replSet "rs0" --bind_ip 0.0.0.0

  mongo-03:
    networks:
      dockerproxy_default:
    image: mongo:3
    ports:
      - "27300:27017"
      - "28017"
    expose:
      - "27017"
    logging:
      options:
        max-size: "500k"
    volumes:
      - ./data/db-2:/data/db
    environment:
      - VIRTUAL_HOST=mongo-03.db.dnt.local
      - VIRTUAL_PORT=28017
    command: --noauth --httpinterface --replSet "rs0" --bind_ip 0.0.0.0

networks:
  dockerproxy_default:
    external: true
