version: '2'

services:
  mongo:
    network_mode: 'bridge'
    build: .
    logging:
      options:
        max-size: "500k"
    depends_on:
      - mongo-01
      - mongo-02
      - mongo-03
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_S3_BUCKET_NAME=turistforeningen
      - AWS_S3_BUCKET_PATH=/backups/mongo/
      - 'MONGO_RS_MEMBERS=mongo-01.db.dnt.local:27100,mongo-02.db.dnt.local:27200'
      - 'MONGO_RS_ARBITERS=mongo-03.db.dnt.local:27300'
    extra_hosts:
      - "mongo-01.db.dnt.local:${DOCKER_IP}"
      - "mongo-02.db.dnt.local:${DOCKER_IP}"
      - "mongo-03.db.dnt.local:${DOCKER_IP}"
    volumes:
      - .:/app
      - ./dump:/dump
      - ./secrets:/secrets
      - ./data:/data

  mongo-01:
    image: mongo:3
    expose:
      - "27017"
    network_mode: 'bridge'
    logging:
      options:
        max-size: "500k"
    ports:
      - "27100:27017"
      - "28017"
    volumes:
      - ./data/db-01:/data/db
    environment:
      - VIRTUAL_HOST=mongo-01.db.dnt.local
      - VIRTUAL_PORT=28017
    extra_hosts:
      - "mongo-01.db.dnt.local:${DOCKER_IP}"
      - "mongo-02.db.dnt.local:${DOCKER_IP}"
      - "mongo-03.db.dnt.local:${DOCKER_IP}"
    command: --noauth --httpinterface --replSet "rs0" --bind_ip 0.0.0.0

  mongo-02:
    network_mode: 'bridge'
    image: mongo:3
    ports:
      - "27200:27017"
      - "28017"
    expose:
      - "27017"
    logging:
      options:
        max-size: "500k"
    volumes:
      - ./data/db-02:/data/db
    environment:
      - VIRTUAL_HOST=mongo-02.db.dnt.local
      - VIRTUAL_PORT=28017
    extra_hosts:
      - "mongo-01.db.dnt.local:${DOCKER_IP}"
      - "mongo-02.db.dnt.local:${DOCKER_IP}"
      - "mongo-03.db.dnt.local:${DOCKER_IP}"
    command: --noauth --httpinterface --replSet "rs0" --bind_ip 0.0.0.0

  mongo-03:
    image: mongo:3
    network_mode: 'bridge'
    ports:
      - "27300:27017"
      - "28017"
    expose:
      - "27017"
    logging:
      options:
        max-size: "500k"
    volumes:
      - ./data/db-03:/data/db
    environment:
      - VIRTUAL_HOST=mongo-03.db.dnt.local
      - VIRTUAL_PORT=28017
    extra_hosts:
      - "mongo-01.db.dnt.local:${DOCKER_IP}"
      - "mongo-02.db.dnt.local:${DOCKER_IP}"
      - "mongo-03.db.dnt.local:${DOCKER_IP}"
    command: --noauth --httpinterface --replSet "rs0" --bind_ip 0.0.0.0

  nosqlclient:
    image: turistforeningen/nosqlclient:latest
    depends_on:
      - mongo
    links:
      - mongo
    network_mode: 'bridge'
    ports:
      - "3000"
    environment:
      - VIRTUAL_HOST=nosqlclient.app.dnt.local
      - VIRTUAL_PORT=3000
      - MONGO_URL=mongodb://mongo:27017
      # - MONGOCLIENT_AUTH=true
      # - MONGOCLIENT_USERNAME=admin
      # - MONGOCLIENT_PASSWORD=admin
    extra_hosts:
      - "mongo-01.db.dnt.local:${DOCKER_IP}"
      - "mongo-02.db.dnt.local:${DOCKER_IP}"
      - "mongo-03.db.dnt.local:${DOCKER_IP}"
    logging:
      options:
        max-size: "500k"
